In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import tensorflow as tf
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Sequential
import warnings
warnings.filterwarnings("ignore")
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: l

/kaggle/input/coffee-roasting-dataset/Coffee_Roasting.csv


## **Dataset Source**
> This dataset is from the DeepLearning.ai coursera [Advance Learning Algorithms](https://www.coursera.org/learn/advanced-learning-algorithms) course. It is normalized and does not contain any null values.

In [2]:
df=pd.read_csv("/kaggle/input/coffee-roasting-dataset/Coffee_Roasting.csv")
df.drop(columns=df.columns[0], axis=1, inplace=True)

In [3]:
df.tail(10)

Temperature  Duration  Target
199990     0.768273  0.519035     0.0
199991    -1.680748 -1.019054     0.0
199992    -1.672765  1.504299     0.0
199993    -0.919506 -1.104734     1.0
199994     0.249709 -0.991014     1.0
199995     0.127972  1.655843     0.0
199996     1.200146 -0.842043     0.0
199997     1.376723 -0.295213     0.0
199998     0.048600 -0.559008     1.0
199999     1.659754 -0.622457     0.0

In [4]:
df.describe()

Temperature      Duration         Target
count  2.000000e+05  2.000000e+05  200000.000000
mean  -3.471650e-07 -1.268900e-07       0.215000
std    1.000002e+00  1.000003e+00       0.410823
min   -1.685219e+00 -1.699671e+00       0.000000
25%   -8.490226e-01 -8.505646e-01       0.000000
50%    3.965173e-02 -1.424916e-01       0.000000
75%    8.518358e-01  8.696861e-01       0.000000
max    1.659754e+00  1.793239e+00       1.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   Temperature  200000 non-null  float64
 1   Duration     200000 non-null  float64
 2   Target       200000 non-null  float64
dtypes: float64(3)
memory usage: 4.6 MB


In [6]:
tf.random.set_seed(1234)
model = Sequential([
    tf.keras.Input(shape=(2,)),
    Dense(3,activation="sigmoid",name="layer1"),
    Dense(1,activation="sigmoid",name="layer2"),
])

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (None, 3)                 9         
                                                                 
 layer2 (Dense)              (None, 1)                 4         
                                                                 
Total params: 13
Trainable params: 13
Non-trainable params: 0
_________________________________________________________________


In [8]:
W1,b1 = model.get_layer("layer1").get_weights()
W2,b2 = model.get_layer("layer2").get_weights()
print(f"W1{W1.shape}:\n",W1,f"\nb1{b1.shape}:",b1)
print(f"W2{W2.shape}:\n",W2,f"\nb2{b2.shape}:",b2)

W1(2, 3):
 [[-0.97378564 -0.88692945  0.46751046]
 [ 0.7680259  -0.7703824  -0.66889   ]] 
b1(3,): [0. 0. 0.]
W2(3, 1):
 [[-0.1073606]
 [-1.023407 ]
 [-0.3291884]] 
b2(1,): [0.]


In [9]:
df.head()
X = df[["Temperature","Duration"]]
Y = df[["Target"]]


In [10]:
model.compile(loss=tf.keras.losses.BinaryCrossentropy(),
             optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),
             )
model.fit(X,Y,epochs=10)

Epoch 1/10
6250/6250 [==============================] - 11s 2ms/step - loss: 0.1732
Epoch 2/10
6250/6250 [==============================] - 9s 1ms/step - loss: 0.1142
Epoch 3/10
6250/6250 [==============================] - 9s 2ms/step - loss: 0.0336
Epoch 4/10
6250/6250 [==============================] - 9s 1ms/step - loss: 0.0152
Epoch 5/10
6250/6250 [==============================] - 9s 2ms/step - loss: 0.0100
Epoch 6/10
6250/6250 [==============================] - 9s 1ms/step - loss: 0.0071
Epoch 7/10
6250/6250 [==============================] - 9s 1ms/step - loss: 0.0050
Epoch 8/10
6250/6250 [==============================] - 9s 1ms/step - loss: 0.0036
Epoch 9/10
6250/6250 [==============================] - 9s 1ms/step - loss: 0.0026
Epoch 10/10
6250/6250 [==============================] - 9s 1ms/step - loss: 0.0019


In [11]:
W1,b1=model.get_layer("layer1").get_weights()
W2,b2=model.get_layer("layer2").get_weights()
print("W1:\n",W1,"\nb1:",b1)
print("W2:\n",W2,"\nb2:",b2)

W1:
 [[ 14.430299   -11.041605    -0.1226527 ]
 [ 11.963819    -0.25281817  -8.94731   ]] 
b1: [  1.7976446 -12.031823  -11.203615 ]
W2:
 [[-42.853024]
 [-50.45287 ]
 [-46.095837]] 
b2: [26.357853]


In [12]:
X_test = np.array([
    [-0.919506,-1.104734],# positive example
    [1.200146,-0.842043]#negative example
])
prediction=model.predict(X_test)
yhat = (prediction >= 0.5).astype(int)
print(f"decisions = \n{yhat}")

1/1 [==============================] - 0s 103ms/step
decisions = 
[[1]
 [0]]
